[versions]

androidTools = "8.1.2"

compileSdk = "34"
minSdk = "21"
targetSdk = "33"

jdk-target = "1.8"
jdk-toolchain = "17"

androidx-activity = "1.6.1"
androidx-appcompat = "1.6.1"
androidx-benchmark = "1.1.1"
androidx-cardview = "1.0.0"
androidx-compose-compiler = "1.5.3"
# see https://developer.android.com/jetpack/compose/bom/bom-mapping
androidx-compose-bom = "2023.01.00"
androidx-constraintlayout = "2.1.4"
androidx-core = "1.10.0"
androidx-fragment = "1.3.6"
androidx-gridlayout = "1.0.0"
androidx-lifecycle = "2.6.1"
androidx-navigation = "2.4.0-alpha09"
androidx-paging = "3.0.1"
androidx-profileinstaller = "1.2.0-alpha02"
androidx-recyclerview = "1.3.2"
androidx-room = "2.4.0-alpha04"
androidx-savedstate = "1.2.1"
androidx-startup = "1.1.0"
androidx-test = "1.5.0"
androidx-test-espresso = "3.5.1"
androidx-test-junit-ext = "1.1.5"
androidx-test-runner = "1.5.2"
androidx-test-truth-ext = "1.5.0"
androidx-tracing = "1.1.0"
androidx-transition = "1.4.1"

detekt = "1.19.0"
dokka = "1.9.10"
dependencyGuard = "0.4.3"

google-accompanist = "0.18.0"
google-dagger = "2.40.5"
google-ksp = "1.9.10-1.0.13"
google-material = "1.4.0"

groovy = "3.0.9"
jUnit = "4.13.2"
java-diff-utils = "4.12"
javaParser = "3.24.0"
kgx = "0.1.6"
kotest = "5.1.0"
# Keep this in sync with what is hard-coded in build-logic/settings.gradle.kts as that is upstream
# of loading the library versions from this file but should be the same.
kotlin = "1.9.10"

kotlinx-binary-compatibility = "0.13.2"
kotlinx-coroutines = "1.7.3"
kotlinx-serialization-json = "1.6.0"
kotlinx-atomicfu = "0.22.0"

ktlint = "0.49.1"
ktlint-gradle = "0.1.8"
material = "1.3.0"

mockito-core = "3.12.4"
mockito-kotlin = "3.2.0"

mockk = "1.13.5"
robolectric = "4.10.3"

rxjava2-android = "2.1.1"
rxjava2-core = "2.2.21"

squareup-curtains = "1.2.4"
squareup-cycler = "0.1.9"
squareup-leakcanary = "2.12"
squareup-moshi = "1.15.0"
squareup-okhttp = "4.9.1"
squareup-okio = "3.3.0"
squareup-radiography = "2.4.1"
squareup-retrofit = "2.9.0"
squareup-seismic = "1.0.3"
squareup-workflow = "1.0.0"

timber = "5.0.1"
truth = "1.1.5"
turbine = "1.0.0"
vanniktech-publish = "0.25.3"

[plugins]

kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }

dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }

dropbox-dependencyGuard = { id = "com.dropbox.dependency-guard", version.ref = "dependencyGuard" }

google-ksp = { id = "com.google.devtools.ksp", version.ref = "google-ksp" }

kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ktlint = { id = "com.rickbusarow.ktlint", version.ref = "ktlint-gradle" }
kotlinx-apiBinaryCompatibility = { id = "org.jetbrains.kotlinx.binary-compatibility-validator", version.ref = "kotlinx-binary-compatibility" }
mavenPublish = { id = "com.vanniktech.maven.publish", version.ref = "vanniktech-publish" }

[libraries]

android-gradle-plugin = { module = "com.android.tools.build:gradle", version.ref = "androidTools" }

androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }
androidx-activity-core = { module = "androidx.activity:activity", version.ref = "androidx-activity" }
androidx-activity-ktx = { module = "androidx.activity:activity-ktx", version.ref = "androidx-activity" }

androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx-appcompat" }

androidx-cardview = { module = "androidx.cardview:cardview", version.ref = "androidx-cardview" }

androidx-compose-compiler = { module = "androidx.compose.compiler:compiler", version.ref = "androidx-compose-compiler" }

androidx-compose-bom = { module = "androidx.compose:compose-bom", version.ref = "androidx-compose-bom" }

androidx-compose-foundation = { module = "androidx.compose.foundation:foundation" }
androidx-compose-foundation-layout = { module = "androidx.compose.foundation:foundation-layout" }

androidx-compose-material = { module = "androidx.compose.material:material" }

androidx-compose-runtime = { module = "androidx.compose.runtime:runtime" }
androidx-compose-runtime-saveable = { module = "androidx.compose.runtime:runtime-saveable" }

androidx-compose-ui = { module = "androidx.compose.ui:ui" }
androidx-compose-ui-geometry = { module = "androidx.compose.ui:ui-geometry" }
androidx-compose-ui-graphics = { module = "androidx.compose.ui:ui-graphics" }
androidx-compose-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4" }
androidx-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
androidx-compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }

androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "androidx-constraintlayout" }

androidx-core = { module = "androidx.core:core-ktx", version.ref = "androidx-core" }

androidx-fragment-core = { module = "androidx.fragment:fragment", version.ref = "androidx-fragment" }
androidx-fragment-ktx = { module = "androidx.fragment:fragment-ktx", version.ref = "androidx-fragment" }

androidx-gridlayout = { module = "androidx.gridlayout:gridlayout", version.ref = "androidx-gridlayout" }

androidx-lifecycle-common = { module = "androidx.lifecycle:lifecycle-common", version.ref = "androidx-lifecycle" }
androidx-lifecycle-core = { module = "androidx.lifecycle:lifecycle-runtime", version.ref = "androidx-lifecycle" }
androidx-lifecycle-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "androidx-lifecycle" }
androidx-lifecycle-testing = { module = "androidx.lifecycle:lifecycle-runtime-testing", version.ref = "androidx-lifecycle" }
androidx-lifecycle-viewmodel-core = { module = "androidx.lifecycle:lifecycle-viewmodel", version.ref = "androidx-lifecycle" }
androidx-lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "androidx-lifecycle" }
androidx-lifecycle-viewmodel-savedstate = { module = "androidx.lifecycle:lifecycle-viewmodel-savedstate", version.ref = "androidx-lifecycle" }

androidx-macro-benchmark = { module = "androidx.benchmark:benchmark-macro-junit4", version.ref = "androidx-benchmark" }

androidx-profileinstaller = { module = "androidx.profileinstaller:profileinstaller", version.ref = "androidx-profileinstaller" }

androidx-recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "androidx-recyclerview" }

androidx-savedstate = { module = "androidx.savedstate:savedstate", version.ref = "androidx-savedstate" }

androidx-test-core = { module = "androidx.test:core", version.ref = "androidx-test" }
androidx-test-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "androidx-test-espresso" }
androidx-test-espresso-idlingResource = { module = "androidx.test.espresso:espresso-idling-resource", version.ref = "androidx-test-espresso" }
androidx-test-espresso-intents = { module = "androidx.test.espresso:espresso-intents", version.ref = "androidx-test-espresso" }
androidx-test-junit = { module = "androidx.test.ext:junit", version.ref = "androidx-test-junit-ext" }
androidx-test-runner = { module = "androidx.test:runner", version.ref = "androidx-test-runner" }
androidx-test-truth = { module = "androidx.test.ext:truth", version.ref = "androidx-test-truth-ext" }

androidx-test-uiautomator = "androidx.test.uiautomator:uiautomator:2.2.0"

androidx-tracing-core = { module = "androidx.tracing:tracing", version.ref = "androidx-tracing" }
androidx-tracing-ktx = { module = "androidx.tracing:tracing-ktx", version.ref = "androidx-tracing" }

androidx-transition = { module = "androidx.transition:transition", version.ref = "androidx-transition" }

androidx-viewbinding = { module = "androidx.databinding:viewbinding", version.ref = "androidTools" }

dokka-gradle-plugin = { module = "org.jetbrains.dokka:dokka-gradle-plugin", version.ref = "dokka" }

dropbox-dependencyGuard = { module = "com.dropbox.dependency-guard:dependency-guard", version.ref = "dependencyGuard" }

google-android-material = { module = "com.google.android.material:material", version.ref = "material" }
google-ksp = { module = "com.google.devtools.ksp:symbol-processing-gradle-plugin", version.ref = "google-ksp" }

hamcrest = "org.hamcrest:hamcrest-core:2.2"

java-diff-utils = { module = "io.github.java-diff-utils:java-diff-utils", version.ref = "java-diff-utils" }

jetbrains-annotations = "org.jetbrains:annotations:24.0.1"

junit = { module = "junit:junit", version.ref = "jUnit" }

kgx = { module = "com.rickbusarow.kgx:kotlin-gradle-extensions", version.ref = "kgx" }

kotlin-bom = { module = "org.jetbrains.kotlin:kotlin-bom", version.ref = "kotlin" }
kotlin-common = { module = "org.jetbrains.kotlin:kotlin-stdlib-common", version.ref = "kotlin" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-jdk6 = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
kotlin-jdk7 = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk7", version.ref = "kotlin" }
kotlin-jdk8 = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }
kotlin-serialization-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-serialization", version.ref = "kotlin" }
kotlin-test-annotations = { module = "org.jetbrains.kotlin:kotlin-test-annotations-common", version.ref = "kotlin" }
kotlin-test-common = { module = "org.jetbrains.kotlin:kotlin-test-common", version.ref = "kotlin" }
kotlin-test-core = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlin-test-jdk = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }

kotlinx-binaryCompatibility-gradle-plugin = { module = "org.jetbrains.kotlinx:binary-compatibility-validator", version.ref = "kotlinx-binary-compatibility" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-rx2 = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-rx2", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-test-common = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization-json" }
kotlinx-atomicfu = { module = "org.jetbrains.kotlinx:atomicfu", version.ref = "kotlinx-atomicfu" }

ktlint-core = { module = "com.pinterest.ktlint:ktlint-core", version.ref = "ktlint" }
ktlint-gradle = { module = "com.rickbusarow.ktlint:ktlint-gradle-plugin", version.ref = "ktlint-gradle" }

lanterna = "com.googlecode.lanterna:lanterna:3.1.1"

mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockito-core" }
mockito-kotlin = { module = "org.mockito.kotlin:mockito-kotlin", version.ref = "mockito-kotlin" }

mockk = { module = "io.mockk:mockk", version.ref = "mockk" }

reactivestreams = "org.reactivestreams:reactive-streams:1.0.4"

robolectric = { module = "org.robolectric:robolectric", version.ref = "robolectric" }
robolectric-annotations = { module = "org.robolectric:annotations", version.ref = "robolectric" }

rxjava2-rxandroid = { module = "io.reactivex.rxjava2:rxandroid", version.ref = "rxjava2-android" }
rxjava2-rxjava = { module = "io.reactivex.rxjava2:rxjava", version.ref = "rxjava2-core" }

squareup-curtains = { module = "com.squareup.curtains:curtains", version.ref = "squareup-curtains" }

squareup-cycler = { module = "com.squareup.cycler:cycler", version.ref = "squareup-cycler" }

squareup-leakcanary-android = { module = "com.squareup.leakcanary:leakcanary-android", version.ref = "squareup-leakcanary" }
squareup-leakcanary-instrumentation = { module = "com.squareup.leakcanary:leakcanary-android-instrumentation", version.ref = "squareup-leakcanary" }
squareup-leakcanary-objectwatcher-android = { module = "com.squareup.leakcanary:leakcanary-object-watcher-android-core", version.ref = "squareup-leakcanary" }

squareup-moshi = { module = "com.squareup.moshi:moshi", version.ref = "squareup-moshi" }
squareup-moshi-adapters = { module = "com.squareup.moshi:moshi-adapters", version.ref = "squareup-moshi" }
squareup-moshi-codegen = { module = "com.squareup.moshi:moshi-kotlin-codegen", version.ref = "squareup-moshi" }

squareup-okio = { module = "com.squareup.okio:okio", version.ref = "squareup-okio" }

squareup-radiography = { module = "com.squareup.radiography:radiography", version.ref = "squareup-radiography" }

squareup-seismic = { module = "com.squareup:seismic", version.ref = "squareup-seismic" }

timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }

truth = { module = "com.google.truth:truth", version.ref = "truth" }

turbine = { module = "app.cash.turbine:turbine", version.ref = "turbine" }

vanniktech-publish = { module = "com.vanniktech:gradle-maven-publish-plugin", version.ref = "vanniktech-publish" }

[bundles]
