name: Validate Codeowners

on:
  push:
    branches:
      - main
  pull_request:
  merge_group:

jobs:
  codeowners:
    name: Validate Codeowners
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      # https://github.com/marketplace/actions/github-codeowners-validator
      - uses: mszostok/codeowners-validator@7f3f5e28c6d7b8dfae5731e54ce2272ca384592f # v0.7.4
        with:
          # TODO(https://github.com/square/workflow-kotlin/issues/316) Add the owners check
          # back once this is fixed, or we implement a workaround.
          checks: "files,syntax,duppatterns" #,owners
          experimental_checks: "notowned"
          # Wardell is not in the Square org apparently.
          owner_checker_ignored_owners: "@wardellbagby"
          # GitHub access token is required only if the `owners` check is enabled
          github_access_token: "${{ secrets.OWNERS_VALIDATOR_GITHUB_SECRET }}"
